FROM node:16 AS build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM nginx:latest

COPY /public /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
